###########################################################################################################################
# VoiceMT Community Playbooks
# Playbook: Installing Docker and Creating Containers on Debian Buster
# Based on: https://www.digitalocean.com/community ansible playbooks
# Guide: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04
###########################################################################################################################

- hosts: Debian10
  become: yes
  tasks:
   - name: Install aptitude using apt
     apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

   - name: Install prerequisites
     apt: name={{item}} state=latest update_cache=yes
     loop: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']

   - name: Add Docker GPG and Key
     apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

   - name: Docker Repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      state: present
      filename: docker_debian

   - name: Install Docker Community Edition
     apt:
      name: docker-ce
      update_cache: yes
      state: latest

   - name: Install python pip
     apt:
      name:
       - python-pip
       - python-setuptools
      update_cache: yes
      state: latest

   - name: Update repositories
     apt:
      update_cache: yes

   - name: Install Docker module for Python
     pip:
      name: docker
      #executable: pip3